name: nightly
on:
  push:
#  schedule:
#    - cron: "0 0 * * *" # to debug on non main branch, replace schedule and chron with just push

jobs:
  ## ACCEPTANCE TESTS
  kind-acceptance:
    uses: ./.github/workflows/reusable-nightly-releases.yml
    strategy:
      matrix:
        include:
          - { runner: "0", consul-k8s-branch: "release/0.49.x", build-name: "kind-nightly-49", consul-version: "1.13-dev", kind-version: "v1.23.0" }
    with:
      name: ${{matrix.build-name}}
      directory: acceptance/tests
      additional-flags: "-use-kind -kubecontext=kind-dc1 -secondary-kubecontext=kind-dc2 -consul-image=hashicorppreview/consul-enterprise:${{ matrix.consul-version }}"
      gotestsum-version: 1.6.4
      checkout-ref: ${{ matrix.consul-k8s-branch }}
      kind-version: ${{ matrix.kind-version }}
    secrets:
      CONSUL_ENT_LICENSE: ${{ secrets.CONSUL_ENT_LICENSE }}
      DOCKER_USER: ${{ secrets.DOCKER_USER }}
      DOCKER_PASS: ${{ secrets.DOCKER_PASS }}

  ## CONSUL COMPATIBILITY
  acceptance-consul-compatibility:
    uses: ./.github/workflows/reusable-acceptance.yml
    strategy:
      matrix:
        include:
          - { runner: "0", kind-version: "v1.23.0", consul-version: "1.11-dev", consul-k8s-tag: "v0.49.0"}
         # - { runner: "1", kind-version: "v1.23.0", consul-version: "1.12-dev", consul-k8s-tag: "v0.49.0"}
         # - { runner: "2", kind-version: "v1.23.0", consul-version: "1.13-dev", consul-k8s-tag: "v0.49.0"}
    with:
      name: acceptance
      directory: acceptance/tests
      go-version: ${{ needs.get-go-version.outputs.go-version }}
      additional-flags: "-use-kind -kubecontext=kind-dc1 -secondary-kubecontext=kind-dc2 -consul-image=hashicorppreview/consul-enterprise:${{ matrix.consul-version }}"
      gotestsum-version: 1.6.4
      consul-k8s-image: docker.io/hashicorp/consul-k8s-control-plane:0.49
      kind-version: ${{ matrix.kind-version }}
      checkout-ref: ${{ matrix.consul-k8s-tag }}
    secrets:
      CONSUL_ENT_LICENSE: ${{ secrets.CONSUL_ENT_LICENSE }}